
-- Generated by ORDS REST Data Services 19.4.1.r0572045
-- Schema: HSEMAR  Date: Sun May 10 03:55:47 2020 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'HSEMAR',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'hsemar',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest.hsemar.hr',
      p_base_path      => '/rest/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest.hsemar.hr',
      p_pattern        => 'list/:zipCode',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest.hsemar.hr',
      p_pattern        => 'list/:zipCode',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select fname from facility_hqs where fzipcode = :zipCode');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest.hsemar.hr',
      p_pattern        => 'listAndQualityOfMeasure/:zipCode',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest.hsemar.hr',
      p_pattern        => 'listAndQualityOfMeasure/:zipCode',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select FACILITY_HQS.FNAME as HospitalName,MEASURES_TAKEN_HQS.MNAME as MeasureName,QCOMPARE_TO_NATIONAL as CompareToNational FROM QUALITY_PERFORMANCE_HQS,FACILITY_HQS,MEASURES_TAKEN_HQS 
where  FACILITY_HQS.FZIPCODE = :zipCode
and QUALITY_PERFORMANCE_HQS.QSID = MEASURES_TAKEN_HQS.QSID and FACILITY_HQS.FID = MEASURES_TAKEN_HQS.FID 
and QUALITY_PERFORMANCE_HQS.QCOMPARE_TO_NATIONAL = ''Better than the National Benchmark'' order by QUALITY_PERFORMANCE_HQS.QNATIONAL_SCORE');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest.hsemar.hr',
      p_pattern        => 'listAndQualityOfMeasureByCity/:city',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest.hsemar.hr',
      p_pattern        => 'listAndQualityOfMeasureByCity/:city',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select FACILITY_HQS.FNAME as HospitalName,MEASURES_TAKEN_HQS.MNAME as MeasureName,QCOMPARE_TO_NATIONAL as CompareToNational FROM QUALITY_PERFORMANCE_HQS,FACILITY_HQS,MEASURES_TAKEN_HQS 
where  FACILITY_HQS.FCITY = :city
and QUALITY_PERFORMANCE_HQS.QSID = MEASURES_TAKEN_HQS.QSID and FACILITY_HQS.FID = MEASURES_TAKEN_HQS.FID 
and QUALITY_PERFORMANCE_HQS.QCOMPARE_TO_NATIONAL = ''Better than the National Benchmark'' order by QUALITY_PERFORMANCE_HQS.QNATIONAL_SCORE');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest.hsemar.hr',
      p_pattern        => 'listByCity/:city',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest.hsemar.hr',
      p_pattern        => 'listByCity/:city',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select fname from facility_hqs where fcity = :city');

    
        
COMMIT;

END;