ALTER TABLE  "MEASURES_TAKEN_HQS" ADD CONSTRAINT "FK_MEASURES_TAKEN_HQS" FOREIGN KEY ("FID")
	  REFERENCES  "FACILITY_HQS" ("FID") ENABLE
/
ALTER TABLE  "QUALITY_PERFORMANCE_HQS" ADD CONSTRAINT "FK_QUALITY_PERFORMANCE_HQS" FOREIGN KEY ("MID")
	  REFERENCES  "MEASURES_TAKEN_HQS" ("MID") ENABLE
/

