CREATE INDEX  "IDX_MEASURES_TAK_FID" ON  "MEASURES_TAKEN_HQS" ("FID")
/

CREATE UNIQUE INDEX  "PK_FACILITY_FID" ON  "FACILITY_HQS" ("FID")
/

CREATE UNIQUE INDEX  "PK_FOOTNOTES_HQ_FNID" ON  "FOOTNOTES_HQS" ("FNID")
/

CREATE UNIQUE INDEX  "PK_HOSPITAL_ID_HID" ON  "HOSPITAL_DETAILS_HQS" ("HID")
/

CREATE UNIQUE INDEX  "PK_MEASURES_TAK_MID" ON  "MEASURES_TAKEN_HQS" ("MID")
/

CREATE UNIQUE INDEX  "PK_QUALITY_PERF_QSID" ON  "QUALITY_PERFORMANCE_HQS" ("QSID")
/
