CREATE TABLE  "FACILITY_HQS" 
   (	"FID" NUMBER(*,0) NOT NULL ENABLE, 
	"FNAME" VARCHAR2(128) NOT NULL ENABLE, 
	"FADDRESS" VARCHAR2(256), 
	"FCITY" VARCHAR2(96), 
	"FSTATE" VARCHAR2(96), 
	"FZIPCODE" VARCHAR2(32) NOT NULL ENABLE, 
	"FCOUNTY" VARCHAR2(96), 
	"FPHONE" VARCHAR2(20), 
	"FLATITUDE" VARCHAR2(256), 
	"FOWNERSHIP" VARCHAR2(128), 
	"HID" NUMBER, 
	"FLONGITUDE" VARCHAR2(256), 
	"FMODIFIED" DATE, 
	 CONSTRAINT "PK_FACILITY_FID" PRIMARY KEY ("FID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "MEASURES_TAKEN_HQS" 
   (	"MID" NUMBER(*,0) NOT NULL ENABLE, 
	"FID" NUMBER(*,0) NOT NULL ENABLE, 
	"MSTARTDATE" DATE, 
	"MENDDATE" DATE, 
	"MSTART_QUATER" VARCHAR2(20), 
	"MEND_QUATER" VARCHAR2(20), 
	"MNAME" VARCHAR2(50), 
	"MACRONYM" VARCHAR2(30), 
	"FNID" NUMBER, 
	 CONSTRAINT "PK_MEASURES_TAK_MID" PRIMARY KEY ("MID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "QUALITY_PERFORMANCE_HQS" 
   (	"QSID" NUMBER(*,0) NOT NULL ENABLE, 
	"MID" NUMBER(*,0) NOT NULL ENABLE, 
	"QNATIONAL_SCORE" FLOAT(126), 
	"QCOMPARE_TO_NATIONAL" VARCHAR2(100), 
	 CONSTRAINT "PK_QUALITY_PERF_QSID" PRIMARY KEY ("QSID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "HOSPITAL_DETAILS_HQS" 
   (	"HID" NUMBER(*,0) NOT NULL ENABLE, 
	"HNAME" VARCHAR2(128) NOT NULL ENABLE, 
	"HDESC" VARCHAR2(4000), 
	"HQUALITY_RATING" NUMBER, 
	"HMODIFIED" DATE, 
	 CONSTRAINT "PK_HOSPITAL_ID_HID" PRIMARY KEY ("HID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "FOOTNOTES_HQS" 
   (	"FNID" NUMBER(*,0) NOT NULL ENABLE, 
	"F_TEXT" VARCHAR2(4000), 
	"FDATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FMODIFIED" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "PK_FOOTNOTES_HQ_FNID" PRIMARY KEY ("FNID")
  USING INDEX  ENABLE
   )
/

