CREATE OR REPLACE EDITIONABLE TRIGGER  "FACILITY_HQS_TRG"
BEFORE INSERT ON FACILITY_HQS
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.FID IS NULL THEN
      SELECT FACILITY_HQS_SEQ.NEXTVAL INTO :NEW.FID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER  "FACILITY_HQS_TRG" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "FOOTNOTES_HQS_TRG"
BEFORE INSERT ON FOOTNOTES_HQS
FOR EACH ROW
BEGIN
<<COLUMN_SEQUENCES>>
BEGIN
IF INSERTING AND :NEW.FNID IS NULL THEN
SELECT FOOTNOTES_HQS_SEQ.NEXTVAL INTO :NEW.FNID FROM SYS.DUAL;
END IF;
END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER  "FOOTNOTES_HQS_TRG" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "HOSPITAL_DETAILS_HQS_TRG"
BEFORE INSERT ON HOSPITAL_DETAILS_HQS
FOR EACH ROW
BEGIN
<<COLUMN_SEQUENCES>>
BEGIN
IF INSERTING AND :NEW.HID IS NULL THEN
SELECT HOSPITAL_DETAILS_HQS_SEQ.NEXTVAL INTO :NEW.HID FROM SYS.DUAL;
END IF;
END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER  "HOSPITAL_DETAILS_HQS_TRG" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "MEASURES_TAKEN_HQS_TRG"
BEFORE INSERT ON MEASURES_TAKEN_HQS
FOR EACH ROW
BEGIN
<<COLUMN_SEQUENCES>>
BEGIN
IF INSERTING AND :NEW.MID IS NULL THEN
SELECT MEASURES_TAKEN_HQS_SEQ.NEXTVAL INTO :NEW.MID FROM SYS.DUAL;
END IF;
END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER  "MEASURES_TAKEN_HQS_TRG" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "QUALITY_PERFORMANCE_HQS_TRG"
BEFORE INSERT ON "QUALITY_PERFORMANCE_HQS"
FOR EACH ROW
BEGIN
<<COLUMN_SEQUENCES>>
BEGIN
IF INSERTING AND :NEW.QSID IS NULL THEN
SELECT QUALITY_PERFORMANCE_HQS_SEQ.NEXTVAL INTO :NEW.QSID FROM SYS.DUAL;
END IF;
END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER  "QUALITY_PERFORMANCE_HQS_TRG" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "TR_ATIUD_MEASURES_TAKEN_HQS"
BEFORE INSERT or update
  ON MEASURES_TAKEN_HQS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
V_NUM   NUMBER;
BEGIN
IF INSERTING OR UPDATING THEN
select hqs_compare_to_national(:OLD.MACRONYM,:OLD.MSCORE) into V_NUM from dual;
:NEW.QSID:=V_NUM;
END IF;
END;

/
ALTER TRIGGER  "TR_ATIUD_MEASURES_TAKEN_HQS" DISABLE
/