CREATE OR REPLACE FORCE EDITIONABLE VIEW  "HOSPITAL_MEASURES_HQS" ("MID", "MSTARTDATE", "MENDDATE", "MSTART_QUATER", "MEND_QUATER", "MNAME", "MACRONYM", "F_TEXT", "QCOMPARE_TO_NATIONAL", "QNATIONAL_SCORE", "HNAME", "HQUALITY_RATING", "FNAME", "FADDRESS", "FCITY", "FSTATE", "FZIPCODE", "FPHONE", "FLATITUDE", "FOWNERSHIP", "FLONGITUDE") AS 
  select MEASURES_TAKEN_HQS.MID as MID,
    MEASURES_TAKEN_HQS.MSTARTDATE as MSTARTDATE,
    MEASURES_TAKEN_HQS.MENDDATE as MENDDATE,
    MEASURES_TAKEN_HQS.MSTART_QUATER as MSTART_QUATER,
    MEASURES_TAKEN_HQS.MEND_QUATER as MEND_QUATER,
    MEASURES_TAKEN_HQS.MNAME as MNAME,
    MEASURES_TAKEN_HQS.MACRONYM as MACRONYM,
    FOOTNOTES_HQS.F_TEXT as F_TEXT,
    QUALITY_PERFORMANCE_HQS.QCOMPARE_TO_NATIONAL as QCOMPARE_TO_NATIONAL,
    QUALITY_PERFORMANCE_HQS.QNATIONAL_SCORE as QNATIONAL_SCORE,
    HOSPITAL_DETAILS_HQS.HNAME as HNAME,
    HOSPITAL_DETAILS_HQS.HQUALITY_RATING as HQUALITY_RATING,
    FACILITY_HQS.FNAME as FNAME,
    FACILITY_HQS.FADDRESS as FADDRESS,
    FACILITY_HQS.FCITY as FCITY,
    FACILITY_HQS.FSTATE as FSTATE,
    FACILITY_HQS.FZIPCODE as FZIPCODE,
    FACILITY_HQS.FPHONE as FPHONE,
    FACILITY_HQS.FLATITUDE as FLATITUDE,
    FACILITY_HQS.FOWNERSHIP as FOWNERSHIP,
    FACILITY_HQS.FLONGITUDE as FLONGITUDE 
 from FOOTNOTES_HQS FOOTNOTES_HQS,
    QUALITY_PERFORMANCE_HQS QUALITY_PERFORMANCE_HQS,
    MEASURES_TAKEN_HQS MEASURES_TAKEN_HQS,
    HOSPITAL_DETAILS_HQS HOSPITAL_DETAILS_HQS,
    FACILITY_HQS FACILITY_HQS
where FOOTNOTES_HQS.FNID=MEASURES_TAKEN_HQS.FNID(+)
and FACILITY_HQS.FID=MEASURES_TAKEN_HQS.FID(+)
AND HOSPITAL_DETAILS_HQS.HID = FACILITY_HQS.HID(+)
AND QUALITY_PERFORMANCE_HQS.MID=MEASURES_TAKEN_HQS.MID(+)
/

