CREATE OR REPLACE FORCE VIEW "HOSPITAL_MEASURES_HQS_VW" ("MID", "MSTARTDATE", "MENDDATE", "MSTART_QUATER", "MEND_QUATER", "MNAME", "MACRONYM", "MSCORE", "QSID", "F_TEXT", "QCOMPARE_TO_NATIONAL", "QMEASUREID", "FNAME", "FADDRESS", "FCITY", "FSTATE", "FZIPCODE", "FPHONE", "FLATITUDE", "FOWNERSHIP", "FLONGITUDE", "HNAME", "HQUALITY_RATING", "FNID") AS
select MEASURES_TAKEN_HQS.MID as MID,
    MEASURES_TAKEN_HQS.MSTARTDATE as MSTARTDATE,
    MEASURES_TAKEN_HQS.MENDDATE as MENDDATE,
    MEASURES_TAKEN_HQS.MSTART_QUATER as MSTART_QUATER,
    MEASURES_TAKEN_HQS.MEND_QUATER as MEND_QUATER,
    MEASURES_TAKEN_HQS.MNAME as MNAME,
    MEASURES_TAKEN_HQS.MACRONYM as MACRONYM,
        MEASURES_TAKEN_HQS.MSCORE as MSCORE,
		MEASURES_TAKEN_HQS.QSID as QSID,
    FOOTNOTES_HQS.F_TEXT as F_TEXT,
 QUALITY_PERFORMANCE_HQS.QCOMPARE_TO_NATIONAL as QCOMPARE_TO_NATIONAL,
QUALITY_PERFORMANCE_HQS."QMEASUREID" as "QMEASUREID",
FACILITY_HQS.FNAME as FNAME,
FACILITY_HQS.FADDRESS as FADDRESS,
FACILITY_HQS.FCITY as FCITY,
FACILITY_HQS.FSTATE as FSTATE,
FACILITY_HQS.FZIPCODE as FZIPCODE,
FACILITY_HQS.FPHONE as FPHONE,
FACILITY_HQS.FLATITUDE as FLATITUDE,
FACILITY_HQS.FOWNERSHIP as FOWNERSHIP,
FACILITY_HQS.FLONGITUDE as FLONGITUDE,
HOSPITAL_DETAILS_HQS.HNAME as HNAME,
HOSPITAL_DETAILS_HQS.HQUALITY_RATING as HQUALITY_RATING,
FOOTNOTES_HQS.FNID
from FOOTNOTES_HQS FOOTNOTES_HQS,
MEASURES_TAKEN_HQS MEASURES_TAKEN_HQS,
QUALITY_PERFORMANCE_HQS QUALITY_PERFORMANCE_HQS,
FACILITY_HQS FACILITY_HQS,
HOSPITAL_DETAILS_HQS HOSPITAL_DETAILS_HQS
where FOOTNOTES_HQS.FNID(+)=MEASURES_TAKEN_HQS.FNID
AND QUALITY_PERFORMANCE_HQS.QSID(+)=MEASURES_TAKEN_HQS.QSID
and FACILITY_HQS.FID(+)=MEASURES_TAKEN_HQS.FID
AND HOSPITAL_DETAILS_HQS.HID(+) = FACILITY_HQS.HID
/
